# -*- coding: utf-8 -*-
"""automate_Mohamad-Saiful-Rizal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4wqF4Jg-W5gOgK7-35CA1FLpQNxDcBe
"""

import pandas as pd
import joblib
import os

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split


def automate_preprocessing(
    input_path="data_clustering_inverse.csv",
    output_dir="namadataset_preprocessing"
):
    print("=== AUTOMATE PREPROCESSING START ===")

    # Load dataset
    df = pd.read_csv(input_path)
    print(f"Dataset loaded: {df.shape}")

    # Pisahkan fitur dan target
    X = df.drop("Target", axis=1)
    y = df["Target"]

    # Cari kolom kategorikal
    categorical_cols = X.select_dtypes(include=["object"]).columns.tolist()
    print("Categorical columns:", categorical_cols)

    # Label encoding
    label_encoders = {}
    for col in categorical_cols:
        le = LabelEncoder()
        X[col] = le.fit_transform(X[col])
        label_encoders[col] = le

    # Cari kolom numerik
    numerical_cols = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
    print("Numerical columns:", numerical_cols)

    # Standard scaling
    scaler = StandardScaler()
    X[numerical_cols] = scaler.fit_transform(X[numerical_cols])

    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    # Buat folder output
    os.makedirs(output_dir, exist_ok=True)

    # Simpan hasil preprocessing
    joblib.dump(X_train, os.path.join(output_dir, "X_train.joblib"))
    joblib.dump(X_test, os.path.join(output_dir, "X_test.joblib"))
    joblib.dump(y_train, os.path.join(output_dir, "y_train.joblib"))
    joblib.dump(y_test, os.path.join(output_dir, "y_test.joblib"))
    joblib.dump(label_encoders, os.path.join(output_dir, "label_encoders.joblib"))
    joblib.dump(scaler, os.path.join(output_dir, "scaler.joblib"))

    print("Preprocessing selesai dan file tersimpan di:", output_dir)
    print("=== AUTOMATE PREPROCESSING DONE ===")


if __name__ == "__main__":
    automate_preprocessing()
